Repository Anushka-codergirl/Java, pull requests merged in 2020-10, with the labels that each got.

#2 Added pattern programs
  Pattern Programs/Triangle_num_pattern1.java
  Pattern Programs/pyramid patterns/Pattern_1.java
  Pattern Programs/pyramid patterns/Pattern_2.java
  Pattern Programs/pyramid patterns/Pattern_3.java
  Pattern Programs/pyramid patterns/Pattern_4.java
  Pattern Programs/pyramid patterns/Pattern_5.java
Labels: good-to-merge, hacktoberfest-accepted

#7 Added resources to README.md
  ArraysExample/RecursiveBinarySearch.java
  LearningResources/README.md
Labels: good-to-merge, hacktoberfest-accepted

#8 arrayoperation
  arrayoperation
Labels: good-to-merge, hacktoberfest-accepted

#9 Added links to learning resources and ArraytoArrayList
  ArraysExample/ArrayToArrayList.java
  LearningResources/README.md
Labels: good-to-merge, hacktoberfest-accepted

#19 README.md
  LearningResources/README.md
Labels: good-to-merge, hacktoberfest-accepted

#27 Remove duplicates in array example
  ArraysExample/RemoveDuplicatesInArray.java
Labels: good-to-merge, hacktoberfest-accepted

#28 Added Few Lines
  Text Files/src/com/example/textfiles/WritingToFiles.java
Labels: good-to-merge, hacktoberfest-accepted

#33 Added Prims Algorithm with code
  Algorithms/Prims.md
  Algorithms/prims.java
Labels: good-to-merge, hacktoberfest-accepted

#24 PatterOne Added
  Pattern Programs/PatternOne.java
Labels: good-to-merge, hacktoberfest-accepted

#39 Added Merge Sort
  Algorithms/MergeSort.java
  Algorithms/MergeSort.md
Labels: good-to-merge, hacktoberfest-accepted

#36 project based learning links added
  LearningResources/README.md
Labels: hacktoberfest-accepted

#22 Added a pattern KShapeUsingAlgorithms
  Pattern Programs/KShapeUsingAlgorithms/KShapeUsingAlphabets.java
Labels: good first issue, hacktoberfest-accepted

#42 Update README.md in Learning Resources
  LearningResources/README.md
Labels: good-to-merge, hacktoberfest-accepted

#41 Create RecursiveBubbleSort.java
  Algorithms/RecursiveBubbleSort.java
Labels: good-to-merge, hacktoberfest-accepted

#31 Left rotation in an array
  ArraysExample/LeftRotation.java
Labels: good-to-merge, hacktoberfest-accepted

#34 added Pangram code
  Strings/Pangram.java
Labels: hacktoberfest-accepted

#29 Apattern
  Pattern Programs/Alpahabetical_pattern/a_pattern.java
Labels: good-to-merge, hacktoberfest-accepted

#32 Sort int and string arrays
  ArraysExample/SortArrays.java
Labels: good-to-merge, hacktoberfest-accepted

#16 Added Pascals Triangle Pattern implementation
  Pattern Programs/pyramid patterns/PascalTrianglePattern.java
Labels: good-to-merge, hacktoberfest-accepted

#43 added diamond_star_pattern program using java
  Pattern Programs/Diamond_star_pattern.java
Labels: good-to-merge, hacktoberfest-accepted

#37 Adding java learning resources
  LearningResources/README.md
Labels: hacktoberfest-accepted

#30 Npattern
  Pattern Programs/n_pattern.java
Labels: hacktoberfest-accepted

#25 Create MergeArray.java
  ArraysExample/MergeArray.java
Labels: hacktoberfest-accepted

#14 Diamond Pattern implementation in Java
  Pattern Programs/diamondpattern.java
Labels: hacktoberfest-accepted

#45 Added java code on DP.
  Dynamic_programming(DP)/count_Square.java
  Dynamic_programming(DP)/editdistance.java
  Dynamic_programming(DP)/knapsack.java
  Dynamic_programming(DP)/stairCase.java
Labels: good-to-merge, hacktoberfest-accepted
