Repository Anushka-codergirl/Java, pull requests merged in 2022-10, with the labels that each got.

#56 Making Step by Step Documentation Changes
  README.md
Labels: good first issue, hacktoberfest-accepted, good-to-merge

#57 Add ternary example of formatting output
  Programs/InputOutput/TernaryExample.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, good-to-merge

#58 Create HowManyNumbersAreSmallerThantheCurrentNumber
  Programs/ArraysExample/HowManyNumbersAreSmallerThantheCurrentNumber
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, good-to-merge

#59 Created Longest Common Subsequence
  Programs/Dynamic_programming(DP)/longest_common_subsequence.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, good-to-merge

#61 Create InsertionSort.java
  Programs/Algorithms/InsertionSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, good-to-merge

#63 Create Salary.java
  Programs/DataTypes/Salary.java
Labels: hacktoberfest, hacktoberfest-accepted, good-to-merge

#67 Improved Readability
  Programs/Algorithms/LinearSearchExample.java
  Programs/Algorithms/MergeSort.java
  Programs/Algorithms/Prims.java
  Programs/Algorithms/prims.java
  Programs/InputOutput/Example1.java
Labels: hacktoberfest, hacktoberfest-accepted, good-to-merge

#68 Added Minimum Coin Problem in Dynamic_programming folder
  Programs/Dynamic_programming(DP)/MinimumCoinProblem.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, good-to-merge

#73 Created Heap_Sort.java
  Programs/Algorithms/Heap_Sort.java
Labels: hacktoberfest, hacktoberfest-accepted

#74 Java Logic and Architecture
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#81 Improved Readability fixed errors
  Programs/ArraysExample/ArrayToArrayList.java
  Programs/ArraysExample/Arrays.java
  Programs/ArraysExample/CompareArrays.java
  Programs/ArraysExample/CopyArrays.java
  Programs/Comments/src/com/example/comments/Comments.java
  Programs/DataTypes/Salary.java
  Programs/DataTypes/StudentRecord.java
  Programs/Decision Structures/src/com/example/decisions/DecisionStructures.java
  Programs/Dynamic_programming(DP)/Knapsack.java
  Programs/Dynamic_programming(DP)/knapsack.java
  Programs/InputOutput/Example1.java
  Programs/InputOutput/TernaryExample.java
  Programs/JavaNIOAPI/CSVFile.java
  Programs/JavaNIOAPI/WalkPattern.java
  Programs/JavaNIOAPI/WritingFiles.java
  Programs/JavaNIOAPI/WritingTextFiles.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, good-to-merge

#79 Added M-coloring solution
  Programs/Backtracking/Mcolor.java
Labels: hacktoberfest, hacktoberfest-accepted, good-to-merge

#83 added 3 algorithms
  Programs/Algorithms/Dikstra.java
  Programs/Algorithms/FloyadsAlgorithm.java
  Programs/Algorithms/kruskal.java
Labels: hacktoberfest-accepted, good-to-merge

#88 added fibonaccisearch
  Programs/fibonaccisearch.java
Labels: hacktoberfest, hacktoberfest-accepted, good-to-merge

#89 Create BucketSort.java
  Programs/Algorithms/BucketSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, good-to-merge
