Repository Anushka-codergirl/Java, pull requests merged in 2024-10, with the labels that each got.

#94 Update Contributors.md
  Contributors.md
Labels: good first issue, hacktoberfest-accepted

#95 Create PasswordValidator.java
  Programs/ArraysExample/PasswordValidator.java
Labels: good-to-merge, hacktoberfest-accepted

#96 Create TestCustomException1.java
  Programs/Methods/TestCustomException1.java
Labels: hacktoberfest-accepted
